version: "3.8"

services:
  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
    depends_on:
      - redis

  redis:
    image: redis
    container_name: ch-redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: bash -c 'exec 6<>/dev/tcp/redis/6379'
      interval: 2s
      retries: 10


  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ch-web
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
     

volumes:
  postgres_data:
  redis_data: